language: objective-c
before_script:
    - brew update
    - brew upgrade xctool
script:
    - xctool -project ./BlurImageProcessor/ALDBlurImageProcessor.xcodeproj -sdk iphonesimulator -scheme ALDBlurImageProcessor test