language: objective-c
before_script:
    - brew update
    - brew upgrade xctool
script:
    - cd BlurImageProcessor
    - pod install
    - xctool -project ALDBlurImageProcessor.xcodeproj -sdk iphonesimulator -scheme ALDBlurImageProcessor test