language: objective-c
before_script:
    - brew update
    - brew install xctool && brew cleanup xctool
script:
    - cd BlurImageProcessor
    - pod install
    - xctool -workspace ALDBlurImageProcessor.xcworkspace -sdk iphonesimulator -scheme ALDBlurImageProcessor test
